In [8]:
import numpy as np
import tensorflow as tf
a = tf.constant([2., 4., 5.])
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [9]:
a.numpy()

array([2., 4., 5.], dtype=float32)

In [10]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4., 16., 25.], dtype=float32)>

In [11]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)