In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [9]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x, y in dataset:
  print("X:", x.numpy()) 
  print("Y:", y.numpy())

X: [[5 6 7 8]
 [0 1 2 3]]
Y: [[9]
 [4]]
X: [[3 4 5 6]
 [1 2 3 4]]
Y: [[7]
 [5]]
X: [[4 5 6 7]
 [2 3 4 5]]
Y: [[8]
 [6]]
