In [4]:
import tensorflow as tf

In [3]:
def f(w1, w2):
  return 3 * w1 ** 2 + 2 * w1 * w2

w1, w2 = 5, 3
eps = 1e-6
print((f(w1+eps, w2)-f(w1, w2))/eps) 
print((f(w1, w2+eps)-f(w1, w2))/eps) 

36.000003007075065
10.000000003174137


In [17]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
  z = f(w1, w2)
gradients = tape.gradient(z, [w1, w2])
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [8]:
with tf.GradientTape() as tape:
  z = f(w1, w2)
gradients = tape.gradient(z, w1)
# Automatically deletes after tape.gradient
gradients

<tf.Tensor: shape=(), dtype=float32, numpy=36.0>

In [14]:
# Using persistent and deleting tape manually 
with tf.GradientTape(persistent=True) as tape:
  z = f(w1, w2)
gradients_1 = tape.gradient(z, w1)
gradients_2 = tape.gradient(z, w2)
del tape
gradients_1, gradients_2

(<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>)

In [16]:
c1, c2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape() as tape:
  z = f(w1, w2)
gradients = tape.gradient(z, [c1, c2])
# Only tracks variables no constants
gradients

[None, None]

In [18]:
# To stop gradient from backpropagating through some part of a nueral network
def f(w1, w2):
  return 3*w1**2 + tf.stop_gradient(2*w1*w2)
with tf.GradientTape() as tape:
  z = f(w1, w2)
gradients = tape.gradient(z, [w1, w2])
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=30.0>, None]

In [ ]:
# When computing infinity the output would be NaN